### PR TITLE
add name argument to prismaticCodec function AND update to purs 0.14

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by garyb** [comment]
I like it - I think I should have done it this way in the first place, and probably only have the named version.

I'll fix the build and merge this later on today.

**Comment by srghma** [comment]
:+1: agree, I have thought too that this function should replace `prismaticCodec` )

**Comment by srghma** [comment]
updated

**Comment by srghma** [comment]
@garyb added update to purs 0.14

**Comment by thomashoneyman** [comment]
@srghma This needs some work:

1. You'll need to update the bower.json file so that all the dependencies move up by a major version.
2. You'll need to update the package.json file to move `pulp` to ^15.0.0, `purescript` to ^0.14.0, and `psa` to ^0.8.2
3. You also need to update the test modules -- you've only updated the source.

If you don't have time at the moment I can take care of this tomorrow. Just let me know!

**Comment by thomashoneyman** [comment]
I've added a migration to PureScript 0.14 here:
https://github.com/garyb/purescript-codec-argonaut/pull/35

It doesn't include the `prismaticCodec` function, so it doesn't close this PR.

**Comment by srghma** [comment]
tnx everyone! sorry didnt fix in time) trying to not touch computer)

**Comment by thomashoneyman** [comment]
No problem! Thanks for getting it started!

**Pull request closed without merging**
